import { DEFAULT, STR_HOR, STR_VER, COR_ONE, COR_TWO, COR_THR, COR_FOU, ROU_ONE, ROU_TWO, ROU_THR, ROU_FOU } from "./structure";

export const NUM_0 = [
    [COR_ONE, STR_HOR, STR_HOR, COR_TWO],
    [STR_VER, COR_ONE, COR_TWO, STR_VER],
    [STR_VER, STR_VER, STR_VER, STR_VER],
    [STR_VER, STR_VER, STR_VER, STR_VER],
    [STR_VER, COR_THR, COR_FOU, STR_VER],
    [COR_THR, STR_HOR, STR_HOR, COR_FOU]
];

export const NUM_1 = [
    [COR_ONE, STR_HOR, COR_TWO, DEFAULT],
    [COR_THR, COR_TWO, STR_VER, DEFAULT],
    [DEFAULT, STR_VER, STR_VER, DEFAULT],
    [DEFAULT, STR_VER, STR_VER, DEFAULT],
    [COR_ONE, COR_FOU, COR_THR, COR_TWO],
    [COR_THR, STR_HOR, STR_HOR, COR_FOU]
];

export const NUM_2 = [
    [COR_ONE, STR_HOR, STR_HOR, COR_TWO],
    [COR_THR, STR_HOR, COR_TWO, STR_VER],
    [COR_ONE, STR_HOR, COR_FOU, STR_VER],
    [STR_VER, COR_ONE, STR_HOR, COR_FOU],
    [STR_VER, COR_THR, STR_HOR, COR_TWO],
    [COR_THR, STR_HOR, STR_HOR, COR_FOU]
];

export const NUM_3 = [
    [COR_ONE, STR_HOR, STR_HOR, COR_TWO],
    [COR_THR, STR_HOR, COR_TWO, STR_VER],
    [COR_ONE, STR_HOR, COR_FOU, STR_VER],
    [COR_THR, STR_HOR, COR_TWO, STR_VER],
    [COR_ONE, STR_HOR, COR_FOU, STR_VER],
    [COR_THR, STR_HOR, STR_HOR, COR_FOU]
];

export const NUM_4 = [
    [COR_ONE, COR_TWO, COR_ONE, COR_TWO],
    [STR_VER, STR_VER, STR_VER, STR_VER],
    [STR_VER, COR_THR, COR_FOU, STR_VER],
    [COR_THR, STR_HOR, COR_TWO, STR_VER],
    [DEFAULT, DEFAULT, STR_VER, STR_VER],
    [DEFAULT, DEFAULT, COR_THR, COR_FOU]
];

export const NUM_5 = [
    [COR_ONE, STR_HOR, STR_HOR, COR_TWO],
    [STR_VER, COR_ONE, STR_HOR, COR_FOU],
    [STR_VER, COR_THR, STR_HOR, COR_TWO],
    [COR_THR, STR_HOR, COR_TWO, STR_VER],
    [COR_ONE, STR_HOR, COR_FOU, STR_VER],
    [COR_THR, STR_HOR, STR_HOR, COR_FOU]
];

export const NUM_6 = [
    [COR_ONE, STR_HOR, STR_HOR, COR_TWO],
    [STR_VER, COR_ONE, STR_HOR, COR_FOU],
    [STR_VER, COR_THR, STR_HOR, COR_TWO],
    [STR_VER, COR_ONE, COR_TWO, STR_VER],
    [STR_VER, COR_THR, COR_FOU, STR_VER],
    [COR_THR, STR_HOR, STR_HOR, COR_FOU]
];

export const NUM_7 = [
    [COR_ONE, STR_HOR, STR_HOR, COR_TWO],
    [COR_THR, STR_HOR, COR_TWO, STR_VER],
    [DEFAULT, DEFAULT, ROU_TWO, ROU_TWO],
    [DEFAULT, ROU_THR, ROU_THR, DEFAULT],
    [DEFAULT, STR_VER, STR_VER, DEFAULT],
    [DEFAULT, COR_THR, COR_FOU, DEFAULT]
];

export const NUM_8 = [
    [COR_ONE, STR_HOR, STR_HOR, COR_TWO],
    [STR_VER, COR_ONE, COR_TWO, STR_VER],
    [ROU_ONE, COR_THR, COR_FOU, ROU_TWO],
    [ROU_THR, COR_ONE, COR_TWO, ROU_FOU],
    [STR_VER, COR_THR, COR_FOU, STR_VER],
    [COR_THR, STR_HOR, STR_HOR, COR_FOU]
];

export const NUM_9 = [
    [COR_ONE, STR_HOR, STR_HOR, COR_TWO],
    [STR_VER, COR_ONE, COR_TWO, STR_VER],
    [STR_VER, COR_THR, COR_FOU, STR_VER],
    [COR_THR, STR_HOR, COR_TWO, STR_VER],
    [COR_ONE, STR_HOR, COR_FOU, STR_VER],
    [COR_THR, STR_HOR, STR_HOR, COR_FOU]
];

export const NUMBERS = [
    NUM_0, NUM_1, NUM_2,
    NUM_3, NUM_4, NUM_5,
    NUM_6, NUM_7, NUM_8,
    NUM_9
];